//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accountbalancesreport {
            get {
                object obj = ResourceManager.GetObject("accountbalancesreport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accountdetails2 {
            get {
                object obj = ResourceManager.GetObject("accountdetails2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accountheadbalance2 {
            get {
                object obj = ResourceManager.GetObject("accountheadbalance2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accountHeadsBalance {
            get {
                object obj = ResourceManager.GetObject("accountHeadsBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accountmanagement2 {
            get {
                object obj = ResourceManager.GetObject("accountmanagement2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accounts {
            get {
                object obj = ResourceManager.GetObject("accounts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accountsTreeview {
            get {
                object obj = ResourceManager.GetObject("accountsTreeview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accruedexpense {
            get {
                object obj = ResourceManager.GetObject("accruedexpense", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9972c700-6bb9-475d-bfa3-f56352862abc.
        /// </summary>
        internal static string AccruedExpenseAccount {
            get {
                return ResourceManager.GetString("AccruedExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bef3fce3-55b5-414b-aa8b-45f274ba44f0.
        /// </summary>
        internal static string AccruedExpensesSubHead {
            get {
                return ResourceManager.GetString("AccruedExpensesSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8dc3670b-b205-4537-b005-8825cbf6cc4d.
        /// </summary>
        internal static string AccruedPayablesSubHead {
            get {
                return ResourceManager.GetString("AccruedPayablesSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addemployee {
            get {
                object obj = ResourceManager.GetObject("addemployee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addOilDealImage {
            get {
                object obj = ResourceManager.GetObject("addOilDealImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addOilDealImage2 {
            get {
                object obj = ResourceManager.GetObject("addOilDealImage2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addrepairitem {
            get {
                object obj = ResourceManager.GetObject("addrepairitem", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24b5c5e6-0aa1-46d4-8fab-47167ad6a0a6.
        /// </summary>
        internal static string AdminExpenses {
            get {
                return ResourceManager.GetString("AdminExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alarm_48 {
            get {
                object obj = ResourceManager.GetObject("alarm_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated1 {
            get {
                object obj = ResourceManager.GetObject("animated1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated2 {
            get {
                object obj = ResourceManager.GetObject("animated2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated3 {
            get {
                object obj = ResourceManager.GetObject("animated3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated4 {
            get {
                object obj = ResourceManager.GetObject("animated4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated5 {
            get {
                object obj = ResourceManager.GetObject("animated5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated6 {
            get {
                object obj = ResourceManager.GetObject("animated6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated7 {
            get {
                object obj = ResourceManager.GetObject("animated7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated8 {
            get {
                object obj = ResourceManager.GetObject("animated8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap animated9 {
            get {
                object obj = ResourceManager.GetObject("animated9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap appusers {
            get {
                object obj = ResourceManager.GetObject("appusers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap assetsBalance {
            get {
                object obj = ResourceManager.GetObject("assetsBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e859e942-e56a-4d3c-b984-3f39a1961ad3.
        /// </summary>
        internal static string AssetsExpensesSubHead {
            get {
                return ResourceManager.GetString("AssetsExpensesSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 84502527-322a-49ea-b996-12a97df8e6cf.
        /// </summary>
        internal static string AssetsHead {
            get {
                return ResourceManager.GetString("AssetsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap atomix_user31 {
            get {
                object obj = ResourceManager.GetObject("atomix_user31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 726a54a9-48c8-46b6-a25b-99f5620b64e7.
        /// </summary>
        internal static string Banks {
            get {
                return ResourceManager.GetString("Banks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banks1 {
            get {
                object obj = ResourceManager.GetObject("banks1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6f2d35a2-e573-48dc-b5ea-44fc9bb062e3.
        /// </summary>
        internal static string BardanaSellingExpenseAccount {
            get {
                return ResourceManager.GetString("BardanaSellingExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Briefcase_50px {
            get {
                object obj = ResourceManager.GetObject("Briefcase_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap broker {
            get {
                object obj = ResourceManager.GetObject("broker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1a78bb87-4188-4456-9564-e9d6e484638c.
        /// </summary>
        internal static string BrokeryExpenseAccount {
            get {
                return ResourceManager.GetString("BrokeryExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50e11c2f-a995-4178-b546-915c5e40f426.
        /// </summary>
        internal static string BrokeryExpenseSubHead {
            get {
                return ResourceManager.GetString("BrokeryExpenseSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap capitalaccount1 {
            get {
                object obj = ResourceManager.GetObject("capitalaccount1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7cefb13a-348b-45f8-9301-c3381de40f97.
        /// </summary>
        internal static string CapitalAccountSubHead {
            get {
                return ResourceManager.GetString("CapitalAccountSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f276c771-faa5-47f8-b594-2126ff3ca017.
        /// </summary>
        internal static string CapitalAccountTopHead {
            get {
                return ResourceManager.GetString("CapitalAccountTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cashaccount1 {
            get {
                object obj = ResourceManager.GetObject("cashaccount1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1b052177-4120-4680-b357-d579b3e62edf.
        /// </summary>
        internal static string CashAccountSubHead {
            get {
                return ResourceManager.GetString("CashAccountSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35f79a75-f1db-4aab-a0b9-c23b350fa9f3.
        /// </summary>
        internal static string CashInHand {
            get {
                return ResourceManager.GetString("CashInHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cat2 {
            get {
                object obj = ResourceManager.GetObject("cat2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categoryimage {
            get {
                object obj = ResourceManager.GetObject("categoryimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap catelist {
            get {
                object obj = ResourceManager.GetObject("catelist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap catlist2 {
            get {
                object obj = ResourceManager.GetObject("catlist2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap companyList {
            get {
                object obj = ResourceManager.GetObject("companyList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f24cd4be-f145-4dfb-946a-8e3f3be91bd0.
        /// </summary>
        internal static string CottonSeedLaborExpenseAccount {
            get {
                return ResourceManager.GetString("CottonSeedLaborExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb087364-c2c2-46a1-af6b-a56c95f880a8.
        /// </summary>
        internal static string CottonSeedLaborExpensePayable {
            get {
                return ResourceManager.GetString("CottonSeedLaborExpensePayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b69b6a6a-9fd3-4435-8430-4988517404df.
        /// </summary>
        internal static string Creditors {
            get {
                return ResourceManager.GetString("Creditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap creditors1 {
            get {
                object obj = ResourceManager.GetObject("creditors1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3aebeb1c-bbc0-4495-a301-a91675bb480f.
        /// </summary>
        internal static string CrudeOilWholeSaleLaborExpenseAccount {
            get {
                return ResourceManager.GetString("CrudeOilWholeSaleLaborExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csharpblue {
            get {
                object obj = ResourceManager.GetObject("csharpblue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap csharpwhite {
            get {
                object obj = ResourceManager.GetObject("csharpwhite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to afdb6d2d-b76e-41c3-bbc5-c1c64190ddd8.
        /// </summary>
        internal static string CurrentAssets {
            get {
                return ResourceManager.GetString("CurrentAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d7155c11-63ee-4adf-9986-93f6ea830e68.
        /// </summary>
        internal static string CurrentLiabilities {
            get {
                return ResourceManager.GetString("CurrentLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Customer {
            get {
                object obj = ResourceManager.GetObject("Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customers {
            get {
                object obj = ResourceManager.GetObject("customers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dashboard_50px {
            get {
                object obj = ResourceManager.GetObject("Dashboard_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap daybookentries {
            get {
                object obj = ResourceManager.GetObject("daybookentries", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap daybookentries2 {
            get {
                object obj = ResourceManager.GetObject("daybookentries2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deal_50 {
            get {
                object obj = ResourceManager.GetObject("deal_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deal_list50 {
            get {
                object obj = ResourceManager.GetObject("deal_list50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fd183aa0-dec8-452e-9cf1-e4cc598189de.
        /// </summary>
        internal static string Debtors {
            get {
                return ResourceManager.GetString("Debtors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_52px {
            get {
                object obj = ResourceManager.GetObject("Delete_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_k52px {
            get {
                object obj = ResourceManager.GetObject("Delete_k52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dispatchrepairslist {
            get {
                object obj = ResourceManager.GetObject("dispatchrepairslist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Driver_50px {
            get {
                object obj = ResourceManager.GetObject("Driver_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap efiles {
            get {
                object obj = ResourceManager.GetObject("efiles", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employeelist {
            get {
                object obj = ResourceManager.GetObject("employeelist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap employeepayments {
            get {
                object obj = ResourceManager.GetObject("employeepayments", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 87f12424-ef20-4aed-a0cd-d43800224c73.
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expenseBalance {
            get {
                object obj = ResourceManager.GetObject("expenseBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 71d464d0-3281-4bd5-bbba-2eb381377558.
        /// </summary>
        internal static string ExpensesHead {
            get {
                return ResourceManager.GetString("ExpensesHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap facicon {
            get {
                object obj = ResourceManager.GetObject("facicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap factorylogo {
            get {
                object obj = ResourceManager.GetObject("factorylogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financialexpense {
            get {
                object obj = ResourceManager.GetObject("financialexpense", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27f5b742-048c-4380-b747-552f6f1b7dfb.
        /// </summary>
        internal static string FinancialExpensesTopHead {
            get {
                return ResourceManager.GetString("FinancialExpensesTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffcb4e19-83ee-46db-8e11-ec8ee14c86b7.
        /// </summary>
        internal static string FinancialExpenseSubHead {
            get {
                return ResourceManager.GetString("FinancialExpenseSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap financials {
            get {
                object obj = ResourceManager.GetObject("financials", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fingerprint_96px {
            get {
                object obj = ResourceManager.GetObject("Fingerprint_96px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fingerprint_reader {
            get {
                object obj = ResourceManager.GetObject("fingerprint_reader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e24aeb66-eea9-4eaf-9eeb-31c5459f364b.
        /// </summary>
        internal static string FixedAssets {
            get {
                return ResourceManager.GetString("FixedAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FloorScale {
            get {
                object obj = ResourceManager.GetObject("FloorScale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9f8733b2-08b5-4ce9-b1cf-658a16e93c34.
        /// </summary>
        internal static string FreightExpenseAccount {
            get {
                return ResourceManager.GetString("FreightExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gate_50px {
            get {
                object obj = ResourceManager.GetObject("Gate_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generalaccounts {
            get {
                object obj = ResourceManager.GetObject("generalaccounts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generalexpense {
            get {
                object obj = ResourceManager.GetObject("generalexpense", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 56a26e03-406d-4b65-bf77-cda4a0865d23.
        /// </summary>
        internal static string GeneralExpenseAccount {
            get {
                return ResourceManager.GetString("GeneralExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c315aaac-2462-4ddd-9e37-779ac30d0381.
        /// </summary>
        internal static string GeneralExpenseHead {
            get {
                return ResourceManager.GetString("GeneralExpenseHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generalreceipts {
            get {
                object obj = ResourceManager.GetObject("generalreceipts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap generaltransaction {
            get {
                object obj = ResourceManager.GetObject("generaltransaction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9f36bf8d-754d-40b0-bf0b-7dab78c15061.
        /// </summary>
        internal static string GoodsLossDueToShortQty {
            get {
                return ResourceManager.GetString("GoodsLossDueToShortQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9a2a6398-0bb8-44e5-8942-7945f565fdca.
        /// </summary>
        internal static string HeadAccount {
            get {
                return ResourceManager.GetString("HeadAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hydroelectric_30px {
            get {
                object obj = ResourceManager.GetObject("Hydroelectric_30px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_robot_48 {
            get {
                object obj = ResourceManager.GetObject("icons8_robot_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_robot_96 {
            get {
                object obj = ResourceManager.GetObject("icons8_robot_96", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Steam_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_Steam_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap incomeBalance {
            get {
                object obj = ResourceManager.GetObject("incomeBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 549a52f0-b925-4030-934e-a5052af71583.
        /// </summary>
        internal static string IncomeHead {
            get {
                return ResourceManager.GetString("IncomeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap incomestatement {
            get {
                object obj = ResourceManager.GetObject("incomestatement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b7f550d1-22a5-4388-bafc-bbcb46d09282.
        /// </summary>
        internal static string IncomeTopHead {
            get {
                return ResourceManager.GetString("IncomeTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inventoryitems {
            get {
                object obj = ResourceManager.GetObject("inventoryitems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14095655-3778-4c2c-8bf4-1d34a644c16c.
        /// </summary>
        internal static string InventoryItemsConsumptionExpenseAccount {
            get {
                return ResourceManager.GetString("InventoryItemsConsumptionExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap issuereceive {
            get {
                object obj = ResourceManager.GetObject("issuereceive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23a15a9b-e7e2-4c0e-8429-7a9507d3bd34.
        /// </summary>
        internal static string ItemPurchasedExpenseSubHead {
            get {
                return ResourceManager.GetString("ItemPurchasedExpenseSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 72eb3cf9-ec07-48be-ba82-8ab238659a44.
        /// </summary>
        internal static string ItemPurchasedExpenseTopHead {
            get {
                return ResourceManager.GetString("ItemPurchasedExpenseTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1a60c100-e62c-4454-87b7-fd46d42f67ff.
        /// </summary>
        internal static string ItemsPurchasedAccount {
            get {
                return ResourceManager.GetString("ItemsPurchasedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b1d62010-8414-417b-b8e9-252beb2ec4da.
        /// </summary>
        internal static string LaborExpensePayableSubHead {
            get {
                return ResourceManager.GetString("LaborExpensePayableSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b7b35f04-088c-48f7-978e-506aa5a38681.
        /// </summary>
        internal static string LaborExpenseSubHead {
            get {
                return ResourceManager.GetString("LaborExpenseSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap laborpayableaccounts {
            get {
                object obj = ResourceManager.GetObject("laborpayableaccounts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9317e07a-3ad3-4a39-b47e-724f6de923a5.
        /// </summary>
        internal static string LiabilitiesHead {
            get {
                return ResourceManager.GetString("LiabilitiesHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap liabilityBalance {
            get {
                object obj = ResourceManager.GetObject("liabilityBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lightoff {
            get {
                object obj = ResourceManager.GetObject("lightoff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lighton {
            get {
                object obj = ResourceManager.GetObject("lighton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LOGO3png {
            get {
                object obj = ResourceManager.GetObject("LOGO3png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap longtermasset {
            get {
                object obj = ResourceManager.GetObject("longtermasset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14460fc2-216b-4eb4-8780-0daad319d6e4.
        /// </summary>
        internal static string LongTermAssetsExpensesAccount {
            get {
                return ResourceManager.GetString("LongTermAssetsExpensesAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf5fda68-b35f-4d99-8ec7-9b38a2df4b17.
        /// </summary>
        internal static string LongTermAssetsSubHead {
            get {
                return ResourceManager.GetString("LongTermAssetsSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c5011a59-c59c-47e8-ac16-11ab3d8db531.
        /// </summary>
        internal static string LongTermAssetsTopHead {
            get {
                return ResourceManager.GetString("LongTermAssetsTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a987d189-0919-424d-becb-838d9cf52b52.
        /// </summary>
        internal static string LongTermLiabilities {
            get {
                return ResourceManager.GetString("LongTermLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap maalregister {
            get {
                object obj = ResourceManager.GetObject("maalregister", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min1 {
            get {
                object obj = ResourceManager.GetObject("min1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min2 {
            get {
                object obj = ResourceManager.GetObject("min2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min3 {
            get {
                object obj = ResourceManager.GetObject("min3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min4 {
            get {
                object obj = ResourceManager.GetObject("min4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min5 {
            get {
                object obj = ResourceManager.GetObject("min5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap min6 {
            get {
                object obj = ResourceManager.GetObject("min6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 621a8622-b2d4-4861-b247-8e60abc593e1.
        /// </summary>
        internal static string MiscSellingExpenses {
            get {
                return ResourceManager.GetString("MiscSellingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Office {
            get {
                object obj = ResourceManager.GetObject("Office", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41dfc16b-6338-47bb-ae05-d4fd67903e19.
        /// </summary>
        internal static string OilcakeLaborExpensePayableAccount {
            get {
                return ResourceManager.GetString("OilcakeLaborExpensePayableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f533545c-236b-4603-9894-c641f1bfa57c.
        /// </summary>
        internal static string OilCakeRetailLaborExpenseAccount {
            get {
                return ResourceManager.GetString("OilCakeRetailLaborExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15b564bf-6029-4524-a29d-ff2a8dcaafba.
        /// </summary>
        internal static string OilCakeRetailSaleAccount {
            get {
                return ResourceManager.GetString("OilCakeRetailSaleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6f7bd95-9b56-4af7-87e4-0c91272ebd49.
        /// </summary>
        internal static string OilCakeRetailSubHead {
            get {
                return ResourceManager.GetString("OilCakeRetailSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to becdc94e-7822-4bb2-ae24-7bebe43ed8a2.
        /// </summary>
        internal static string OilCakeSalesSubHead {
            get {
                return ResourceManager.GetString("OilCakeSalesSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7bbc75f5-84db-4cee-a887-ffd934ac31b4.
        /// </summary>
        internal static string OilCakeWholeSaleLaborExpenseAccount {
            get {
                return ResourceManager.GetString("OilCakeWholeSaleLaborExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oilDealListImage {
            get {
                object obj = ResourceManager.GetObject("oilDealListImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oilDirstList {
            get {
                object obj = ResourceManager.GetObject("oilDirstList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oilDirtDeal {
            get {
                object obj = ResourceManager.GetObject("oilDirtDeal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oildirtreportsbtn {
            get {
                object obj = ResourceManager.GetObject("oildirtreportsbtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8107d98a-8041-417d-b3f3-bef4aae15cee.
        /// </summary>
        internal static string OilDirtSubHead {
            get {
                return ResourceManager.GetString("OilDirtSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ebec0a7d-35f0-42cd-be7f-3e6d46e4f996.
        /// </summary>
        internal static string OilDirtWholeSaleLaborExpenseAccount {
            get {
                return ResourceManager.GetString("OilDirtWholeSaleLaborExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap oilreportimage {
            get {
                object obj = ResourceManager.GetObject("oilreportimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f1f1e2ff-de5c-4243-a726-3fe0e775ae9a.
        /// </summary>
        internal static string OilSalesSubHead {
            get {
                return ResourceManager.GetString("OilSalesSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c8bfb6d9-83ec-4b11-97d0-503ad17e69eb.
        /// </summary>
        internal static string OpeningBalanceEquityAccount {
            get {
                return ResourceManager.GetString("OpeningBalanceEquityAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap openingbalancepic {
            get {
                object obj = ResourceManager.GetObject("openingbalancepic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a9d129d4-03d0-4b70-a97e-09f60463e904.
        /// </summary>
        internal static string OpeningBalanceSubHead {
            get {
                return ResourceManager.GetString("OpeningBalanceSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap packingstockfactory {
            get {
                object obj = ResourceManager.GetObject("packingstockfactory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap packingstockfactory2 {
            get {
                object obj = ResourceManager.GetObject("packingstockfactory2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap payrollgive {
            get {
                object obj = ResourceManager.GetObject("payrollgive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4e302d6c-dfdc-4daf-8017-965201cffb7b.
        /// </summary>
        internal static string PettyCash {
            get {
                return ResourceManager.GetString("PettyCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus_25px {
            get {
                object obj = ResourceManager.GetObject("Plus_25px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print {
            get {
                object obj = ResourceManager.GetObject("print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print32 {
            get {
                object obj = ResourceManager.GetObject("print32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product {
            get {
                object obj = ResourceManager.GetObject("product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product2 {
            get {
                object obj = ResourceManager.GetObject("product2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap productlist {
            get {
                object obj = ResourceManager.GetObject("productlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap productlist2 {
            get {
                object obj = ResourceManager.GetObject("productlist2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purchasinglist {
            get {
                object obj = ResourceManager.GetObject("purchasinglist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap readyalarm {
            get {
                object obj = ResourceManager.GetObject("readyalarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap readydashboard {
            get {
                object obj = ResourceManager.GetObject("readydashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap readydeal {
            get {
                object obj = ResourceManager.GetObject("readydeal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap readydeallist {
            get {
                object obj = ResourceManager.GetObject("readydeallist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2eda959e-ffcb-4e4e-90e9-624034751908.
        /// </summary>
        internal static string ReadyGoodsSubHead {
            get {
                return ResourceManager.GetString("ReadyGoodsSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2f65f24a-44a3-4bb8-bee7-f97d8fd31719.
        /// </summary>
        internal static string ReadyGoodsTopHead {
            get {
                return ResourceManager.GetString("ReadyGoodsTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap readyreport {
            get {
                object obj = ResourceManager.GetObject("readyreport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap receivables {
            get {
                object obj = ResourceManager.GetObject("receivables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Receive_Cash_50px {
            get {
                object obj = ResourceManager.GetObject("Receive_Cash_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refreshmentlist {
            get {
                object obj = ResourceManager.GetObject("refreshmentlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5cf8e2d6-01ea-4c35-874b-757f948bab8c.
        /// </summary>
        internal static string RepairExpensesPayableSubHead {
            get {
                return ResourceManager.GetString("RepairExpensesPayableSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77677c0b-2325-4183-abf9-205208d28cde.
        /// </summary>
        internal static string RepairingExpenseAccount {
            get {
                return ResourceManager.GetString("RepairingExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 390c60ba-91b9-47b0-9dcb-34c9ee99fecd.
        /// </summary>
        internal static string RepairingExpenseSubHead {
            get {
                return ResourceManager.GetString("RepairingExpenseSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap repairitems {
            get {
                object obj = ResourceManager.GetObject("repairitems", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap retailbardanapic {
            get {
                object obj = ResourceManager.GetObject("retailbardanapic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d280f4cf-2001-4df7-9d9f-ef15ac574c2f.
        /// </summary>
        internal static string SalariesAccount {
            get {
                return ResourceManager.GetString("SalariesAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e75b4461-5121-49e0-907d-fef201e79c13.
        /// </summary>
        internal static string SalariesSubHead {
            get {
                return ResourceManager.GetString("SalariesSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saleorder {
            get {
                object obj = ResourceManager.GetObject("saleorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saleorderlist {
            get {
                object obj = ResourceManager.GetObject("saleorderlist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saleorderslist {
            get {
                object obj = ResourceManager.GetObject("saleorderslist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2868b4dd-b27b-44e5-bdb5-27395822a743.
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30e2052a-44f7-4e70-b60a-0fad1adfbf0e.
        /// </summary>
        internal static string SalesReturnAccount {
            get {
                return ResourceManager.GetString("SalesReturnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save32 {
            get {
                object obj = ResourceManager.GetObject("save32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Scales_50px {
            get {
                object obj = ResourceManager.GetObject("Scales_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search20green {
            get {
                object obj = ResourceManager.GetObject("search20green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search20white {
            get {
                object obj = ResourceManager.GetObject("search20white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selector {
            get {
                object obj = ResourceManager.GetObject("selector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04618e3c-06b5-45df-91b7-5e8872edd01f.
        /// </summary>
        internal static string SellingExpenses {
            get {
                return ResourceManager.GetString("SellingExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_48px {
            get {
                object obj = ResourceManager.GetObject("Settings_48px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9d481d22-f342-4d38-b627-f754e447c485.
        /// </summary>
        internal static string StockPurchases {
            get {
                return ResourceManager.GetString("StockPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 988dc2f1-6858-4712-bad4-78767ae71a98.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4463f116-a135-4858-aa83-3f689ecce1e6.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bf9982a9-5cf8-40db-9f33-71acc2b5e1bd.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Subtract_52px {
            get {
                object obj = ResourceManager.GetObject("Subtract_52px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7592ae16-e9ad-4482-a9a1-fe0138efaa42.
        /// </summary>
        internal static string TracktorLaborExpenseAccount {
            get {
                return ResourceManager.GetString("TracktorLaborExpenseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96c69a44-c3af-4741-9f08-f5a1676f3bab.
        /// </summary>
        internal static string TracktorLaborPayableAccount {
            get {
                return ResourceManager.GetString("TracktorLaborPayableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transactions {
            get {
                object obj = ResourceManager.GetObject("transactions", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transactions2 {
            get {
                object obj = ResourceManager.GetObject("transactions2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trialCustomerBalance2 {
            get {
                object obj = ResourceManager.GetObject("trialCustomerBalance2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trialCustomers {
            get {
                object obj = ResourceManager.GetObject("trialCustomers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trialCustomersBalance {
            get {
                object obj = ResourceManager.GetObject("trialCustomersBalance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Truck_50px {
            get {
                object obj = ResourceManager.GetObject("Truck_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userimage {
            get {
                object obj = ResourceManager.GetObject("userimage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vehicle {
            get {
                object obj = ResourceManager.GetObject("vehicle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zakat {
            get {
                object obj = ResourceManager.GetObject("zakat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 723a5187-550c-4748-bff5-26a7ff9b7b53.
        /// </summary>
        internal static string ZakatPaidAccount {
            get {
                return ResourceManager.GetString("ZakatPaidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dcd337b7-5406-44e7-8ef8-43437ea010f8.
        /// </summary>
        internal static string ZakatPaidSubHead {
            get {
                return ResourceManager.GetString("ZakatPaidSubHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fd11747c-1914-41fa-ba8e-8c044d784101.
        /// </summary>
        internal static string ZakatPaidTopHead {
            get {
                return ResourceManager.GetString("ZakatPaidTopHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6b012123-97c5-447a-a9c7-c33ed46128aa.
        /// </summary>
        internal static string ZakatPayableAccount {
            get {
                return ResourceManager.GetString("ZakatPayableAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b015fc8-4322-4751-8d9b-c259a55b3e6f.
        /// </summary>
        internal static string ZakatPayableSubHead {
            get {
                return ResourceManager.GetString("ZakatPayableSubHead", resourceCulture);
            }
        }
    }
}
